object Versions {
    const val kotlin = "1.5.21"
    const val gradle = "7.0.1"
    const val core_ktx = "1.6.0"
    const val app_compact = "1.3.1"
    const val material_design = "1.4.0"
    const val constraint_layout = "2.1.0"
    const val junit = "4.13.2"
    const val junit_ext = "1.1.3"
    const val espresso_core = "3.4.0"
    const val navigation = "2.3.5"
    const val card_view = "1.0.0"
    const val room = "2.3.0"
    const val coroutine = "1.4.1"
    const val coroutine_android = "1.4.3"
    const val retrofit = "2.9.0"
    const val logger = "4.9.0"
    const val hilt = "2.36"
    const val lifecycle = "2.3.1"
    const val activity_ktx = "1.3.1"
    const val fragment_ktx = "1.3.6"
    const val annotation = "1.2.0"
}